behaviors:
  MazeBrain:
    trainer_type: ppo

    # How many total training steps to run
    max_steps: 5000000

    # How far into the future we bootstrap returns
    time_horizon: 256

    # How often (in steps) to write TensorBoard summaries
    summary_freq: 1000

    # All of these go under `hyperparameters:`
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # (Optional) your network architecture
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory:
      #   memory_size: 128
      #   sequence_length: 64

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
